import type { DropdownClasses } from "./types";

export const DEFAULT_DROPDOWN_CLASSES: Required<DropdownClasses> = {
  root: "",
  wrapper: "",
  trigger: "",
  triggerText: "",
  content: "",
  optionList: "",
  option: "",
  optionSelected: "",
  optionFocused: "",
  optionDisabled: "",
  chevron: "",
  checkIcon: "",
  clearIcon: "",
  noResults: "",
  label: "",
  error: "text-sm text-red-500 dark:text-red-400 mt-1",
  description: "text-xs text-gray-500 mb-1",
  success: "text-sm text-green-600 dark:text-green-400 mt-1",
  shimmer: "",
  shimmerItem: "",
};

export const UNSTYLED_DROPDOWN_CLASSES: Required<DropdownClasses> = {
  root: "",
  wrapper: "",
  trigger: "",
  triggerText: "",
  content: "",
  optionList: "",
  option: "",
  optionSelected: "",
  optionFocused: "",
  optionDisabled: "",
  chevron: "",
  checkIcon: "",
  clearIcon: "",
  noResults: "",
  label: "",
  error: "",
  description: "",
  success: "",
  shimmer: "",
  shimmerItem: "",
};
