import type { CascadingDropdownClasses } from "./types";

export const DEFAULT_CASCADINGDROPDOWN_CLASSES: Required<CascadingDropdownClasses> = {
  root: "",
  container: "",
  trigger: "flex items-center justify-between gap-2 w-full",
  menu: "min-w-[200px]",
  menuItem: "flex items-center justify-between cursor-pointer",
  menuItemSelected: "",
  menuItemFocused: "",
  menuItemDisabled: "",
  submenu: "min-w-[180px]",
  submenuContainer: "z-[9999]",
  submenuItem: "flex items-center gap-2 cursor-pointer",
  submenuItemSelected: "",
  submenuItemFocused: "",
  label: "",
  error: "",
  chevron: "w-4 h-4 shrink-0 transition-transform duration-200",
  submenuChevron: "w-4 h-4 shrink-0",
  checkIcon: "w-4 h-4 shrink-0",
  checkbox: "w-4 h-4 shrink-0 flex items-center justify-center",
  checkboxChecked: "",
  noResults: "",
  loading: "",
};

export const UNSTYLED_CASCADINGDROPDOWN_CLASSES: Required<CascadingDropdownClasses> = {
  root: "",
  container: "",
  trigger: "",
  menu: "",
  menuItem: "",
  menuItemSelected: "",
  menuItemFocused: "",
  menuItemDisabled: "",
  submenu: "",
  submenuContainer: "",
  submenuItem: "",
  submenuItemSelected: "",
  submenuItemFocused: "",
  label: "",
  error: "",
  chevron: "",
  submenuChevron: "",
  checkIcon: "",
  checkbox: "",
  checkboxChecked: "",
  noResults: "",
  loading: "",
};
