import type { MultiSelectSearchableDropdownClasses } from "./utils/types";

export const DEFAULT_MULTISELECTSEARCHABLEDROPDOWN_CLASSES: Required<MultiSelectSearchableDropdownClasses> = {
  root: "",
  wrapper: "",
  trigger: "",
  triggerText: "",
  content: "",
  optionList: "",
  option: "",
  optionSelected: "",
  optionFocused: "",
  optionDisabled: "",
  chevron: "",
  checkbox: "",
  checkboxChecked: "",
  checkboxIcon: "",
  chip: "",
  chipRemove: "",
  noResults: "",
  loading: "",
  label: "",
  error: "",
  searchInput: "",
  searchInputElement: "",
  searchIcon: "",
  moreCount: "",
};

export const UNSTYLED_MULTISELECTSEARCHABLEDROPDOWN_CLASSES: Required<MultiSelectSearchableDropdownClasses> = {
  root: "",
  wrapper: "",
  trigger: "",
  triggerText: "",
  content: "",
  optionList: "",
  option: "",
  optionSelected: "",
  optionFocused: "",
  optionDisabled: "",
  chevron: "",
  checkbox: "",
  checkboxChecked: "",
  checkboxIcon: "",
  chip: "",
  chipRemove: "",
  noResults: "",
  loading: "",
  label: "",
  error: "",
  searchInput: "",
  searchInputElement: "",
  searchIcon: "",
  moreCount: "",
};
