import type { MultiSelectDropdownClasses } from "./types";

export const DEFAULT_MULTISELECTDROPDOWN_CLASSES: Required<MultiSelectDropdownClasses> = {
  root: "",
  wrapper: "",
  trigger: "",
  triggerText: "",
  content: "",
  optionList: "",
  option: "",
  optionSelected: "",
  optionFocused: "",
  optionDisabled: "",
  chevron: "",
  checkbox: "",
  checkboxChecked: "",
  checkboxIcon: "",
  chip: "",
  chipRemove: "",
  noResults: "",
  label: "",
  error: "",
  shimmer: "",
  shimmerItem: "",
  moreCount: "",
};

export const UNSTYLED_MULTISELECTDROPDOWN_CLASSES: Required<MultiSelectDropdownClasses> = {
  root: "",
  wrapper: "",
  trigger: "",
  triggerText: "",
  content: "",
  optionList: "",
  option: "",
  optionSelected: "",
  optionFocused: "",
  optionDisabled: "",
  chevron: "",
  checkbox: "",
  checkboxChecked: "",
  checkboxIcon: "",
  chip: "",
  chipRemove: "",
  noResults: "",
  label: "",
  error: "",
  shimmer: "",
  shimmerItem: "",
  moreCount: "",
};
