import type { DatePickerClasses } from "./utils/types";

export const DEFAULT_DATEPICKER_CLASSES: Required<DatePickerClasses> = {
  root: "",
  trigger: "flex items-center gap-2 w-full px-3 py-2.5 border border-gray-300 dark:border-gray-600 rounded-lg bg-white dark:bg-gray-800 hover:border-gray-400 dark:hover:border-gray-500 focus:ring-2 focus:ring-blue-500 focus:border-transparent cursor-pointer transition-all text-sm text-gray-900 dark:text-gray-100",
  input: "flex-1 text-left truncate",
  calendarIcon: "w-5 h-5 shrink-0 text-gray-400 dark:text-gray-500",
  clearButton: "p-1 rounded-full hover:bg-gray-100 dark:hover:bg-gray-700 text-gray-400 hover:text-gray-600 dark:hover:text-gray-300 transition-colors shrink-0",
  label: "block text-sm font-medium text-gray-700 dark:text-gray-300 mb-1.5",
  error: "text-sm text-red-500 dark:text-red-400 mt-1.5",
  description: "text-xs text-gray-500 dark:text-gray-400 mb-1.5",
  success: "text-sm text-green-600 dark:text-green-400 mt-1.5",
  calendar: "bg-white dark:bg-gray-800 border border-gray-200 dark:border-gray-700 rounded-xl shadow-xl p-4",
  header: "flex items-center justify-between mb-4",
  monthNav: "flex items-center gap-1",
  navButton: "p-1.5 rounded-lg hover:bg-gray-100 dark:hover:bg-gray-700 transition-colors text-gray-600 dark:text-gray-400 hover:text-gray-900 dark:hover:text-white",
  navButtonDisabled: "opacity-30 cursor-not-allowed hover:bg-transparent",
  monthGrid: "flex gap-8",
  grid: "",
  weekdayHeader: "grid grid-cols-7 mb-2",
  weekday: "text-xs font-semibold text-gray-500 dark:text-gray-400 text-center py-2 uppercase tracking-wide",
  day: "relative w-10 h-10 flex items-center justify-center text-sm font-medium rounded-full cursor-pointer transition-all text-gray-700 dark:text-gray-200 hover:bg-gray-100 dark:hover:bg-gray-700 focus:outline-none focus:ring-2 focus:ring-blue-500 focus:ring-offset-1 dark:focus:ring-offset-gray-800",
  daySelected: "bg-blue-600 text-white hover:bg-blue-700",
  dayToday: "ring-2 ring-blue-500 ring-inset font-semibold",
  dayDisabled: "text-gray-300 dark:text-gray-600 cursor-not-allowed hover:bg-transparent",
  dayOutside: "text-gray-300 dark:text-gray-600",
  dayRangeStart: "bg-blue-600 text-white rounded-r-none",
  dayRangeEnd: "bg-blue-600 text-white rounded-l-none",
  dayRangeMiddle: "bg-blue-100 dark:bg-blue-900/30 rounded-none",
  dayHover: "",
  dayFocused: "ring-2 ring-blue-400",
  dayMarked: "",
  weekNumber: "text-xs text-gray-400 dark:text-gray-500 flex items-center justify-center",
  presets: "flex flex-wrap gap-2 pb-4 mb-4 border-b border-gray-100 dark:border-gray-700",
  presetButton: "px-3 py-1.5 text-xs font-semibold rounded-full bg-gray-100 dark:bg-gray-700 text-gray-700 dark:text-gray-300 hover:bg-gray-200 dark:hover:bg-gray-600 transition-all",
  presetActive: "bg-blue-100 dark:bg-blue-900/40 text-blue-700 dark:text-blue-300 ring-1 ring-blue-300 dark:ring-blue-500",
  footer: "flex justify-center pt-4 mt-4 border-t border-gray-100 dark:border-gray-700",
  todayButton: "flex items-center gap-2 px-4 py-2 text-sm font-semibold text-blue-600 dark:text-blue-400 hover:bg-blue-50 dark:hover:bg-blue-900/20 rounded-lg transition-all",
  markerIndicator: "w-1 h-1 rounded-full bg-blue-500 absolute bottom-1 left-1/2 -translate-x-1/2",
  markerTooltip: "absolute z-50 px-3 py-2 text-xs bg-gray-900 dark:bg-gray-700 text-white rounded-lg shadow-lg max-w-[200px]",
  monthSelect: "flex items-center gap-1 px-2 py-1.5 text-sm font-semibold bg-transparent border-none cursor-pointer text-gray-900 dark:text-gray-200 hover:bg-gray-100 dark:hover:bg-gray-700 rounded-lg transition-colors",
  yearSelect: "flex items-center gap-1 px-2 py-1.5 text-sm font-semibold bg-transparent border-none cursor-pointer text-gray-900 dark:text-gray-200 hover:bg-gray-100 dark:hover:bg-gray-700 rounded-lg transition-colors",
  monthDropdown: "",
  yearDropdown: "",
  dropdownMenu: "absolute z-[60] mt-1 max-h-60 overflow-auto rounded-lg bg-white dark:bg-gray-800 shadow-lg border border-gray-200 dark:border-gray-700 py-1 min-w-[140px]",
  dropdownItem: "flex items-center justify-between w-full px-3 py-2 text-sm text-left text-gray-700 dark:text-gray-200 hover:bg-gray-50 dark:hover:bg-gray-700 cursor-pointer",
  dropdownItemSelected: "bg-blue-50 dark:bg-blue-900/30 text-blue-600 dark:text-blue-400 font-medium",
};

export const UNSTYLED_DATEPICKER_CLASSES: Required<DatePickerClasses> = {
  root: "", trigger: "", input: "", calendarIcon: "", clearButton: "",
  label: "", error: "", description: "", success: "", calendar: "", header: "", monthNav: "",
  navButton: "", navButtonDisabled: "", monthGrid: "", grid: "",
  weekdayHeader: "", weekday: "", day: "", daySelected: "", dayToday: "",
  dayDisabled: "", dayOutside: "", dayRangeStart: "", dayRangeEnd: "",
  dayRangeMiddle: "", dayHover: "", dayFocused: "", dayMarked: "",
  weekNumber: "", presets: "", presetButton: "", presetActive: "",
  footer: "", todayButton: "", markerIndicator: "", markerTooltip: "",
  monthSelect: "", yearSelect: "", monthDropdown: "", yearDropdown: "",
  dropdownMenu: "", dropdownItem: "", dropdownItemSelected: "",
};
