import type { SearchableDropdownClasses } from "./types";

export const DEFAULT_SEARCHABLEDROPDOWN_CLASSES: Required<SearchableDropdownClasses> = {
  root: "",
  wrapper: "",
  trigger: "",
  triggerText: "",
  content: "",
  optionList: "",
  option: "",
  optionSelected: "",
  optionFocused: "",
  optionDisabled: "",
  chevron: "",
  checkIcon: "",
  clearIcon: "",
  noResults: "",
  label: "",
  error: "",
  searchInput: "",
  searchInputElement: "",
  searchIcon: "",
  shimmer: "",
  shimmerItem: "",
};

export const UNSTYLED_SEARCHABLEDROPDOWN_CLASSES: Required<SearchableDropdownClasses> = {
  root: "",
  wrapper: "",
  trigger: "",
  triggerText: "",
  content: "",
  optionList: "",
  option: "",
  optionSelected: "",
  optionFocused: "",
  optionDisabled: "",
  chevron: "",
  checkIcon: "",
  clearIcon: "",
  noResults: "",
  label: "",
  error: "",
  searchInput: "",
  searchInputElement: "",
  searchIcon: "",
  shimmer: "",
  shimmerItem: "",
};
