// Generates src/components/CountryFlag/flags/ - one module per flag holding the
// SVG source, plus a static-specifier map the bundler can code-split.
//
// The SVGs ship inside the package so a default CountryFlag makes no network
// call. They are emitted as JS modules rather than assets on purpose: an asset
// URL would need `new URL(..., import.meta.url)`, which Vite only resolves for
// static literals - with a runtime `code` it silently compiles to undefined,
// and import.meta does not exist in the CJS build at all.
//
//   node scripts/generate-flags.mjs

import { mkdirSync, writeFileSync, rmSync } from "fs";
import { resolve, dirname } from "path";
import { fileURLToPath } from "url";
import { optimize } from "svgo";

const root = resolve(dirname(fileURLToPath(import.meta.url)), "..");
const outDir = resolve(root, "src/components/CountryFlag/flags");

// The curated set. Wikimedia-sourced flags reskin politically-contested codes
// (Afghanistan post-2021, among others); this bucket is the reviewed baseline.
const CURATED_BASE = "https://chumflagscdn.s3.ap-south-1.amazonaws.com/flags";

// Codes absent from the curated bucket, backfilled from lipis/flag-icons (MIT)
// at the same 4x3 ratio. BQ and YT are the Dutch and French tricolours - both
// are constituent territories, so the parent flag is correct, not a placeholder.
const BACKFILL_BASE = "https://raw.githubusercontent.com/lipis/flag-icons/main/flags/4x3";
const BACKFILL = ["bq", "xk", "yt"];

const COUNTRY_SOURCE =
  "https://raw.githubusercontent.com/mledoze/countries/master/countries.json";

async function fetchText(url) {
  const res = await fetch(url);
  if (!res.ok) return null;
  return res.text();
}

async function main() {
  const countries = await (await fetch(COUNTRY_SOURCE)).json();
  const codes = [...new Set(countries.map((c) => c.cca2?.toLowerCase()).filter(Boolean))].sort();

  const flags = new Map();
  const missing = [];
  let rawBytes = 0;
  let optimizedBytes = 0;

  await Promise.all(
    codes.map(async (code) => {
      const base = BACKFILL.includes(code) ? BACKFILL_BASE : CURATED_BASE;
      const svg = await fetchText(`${base}/${code}.svg`);
      if (!svg) {
        missing.push(code);
        return;
      }
      const { data } = optimize(svg, { multipass: true });
      rawBytes += Buffer.byteLength(svg);
      optimizedBytes += Buffer.byteLength(data);
      flags.set(code, data);
    })
  );

  if (missing.length) {
    throw new Error(`no flag asset for: ${missing.sort().join(", ")}`);
  }

  rmSync(outDir, { recursive: true, force: true });
  mkdirSync(outDir, { recursive: true });

  const sorted = [...flags.keys()].sort();
  for (const code of sorted) {
    writeFileSync(
      resolve(outDir, `${code}.ts`),
      `export default ${JSON.stringify(flags.get(code))};\n`
    );
  }

  // Static import specifiers - a template literal here would defeat the
  // bundler's static analysis and collapse every chunk back into one.
  const entries = sorted.map((code) => `  "${code}": () => import("./${code}.js"),`).join("\n");
  writeFileSync(
    resolve(outDir, "index.ts"),
    `// Generated by scripts/generate-flags.mjs - do not edit.\n` +
      `export const FLAG_MODULES: Record<string, () => Promise<{ default: string }>> = {\n` +
      `${entries}\n};\n`
  );

  console.log(
    `[generate-flags] ${sorted.length} flags | ` +
      `${(rawBytes / 1024).toFixed(0)} KB raw -> ${(optimizedBytes / 1024).toFixed(0)} KB optimized`
  );
}

main().catch((err) => {
  console.error("[generate-flags]", err.message);
  process.exit(1);
});
