import type { TimePickerClasses } from "./types";

export const DEFAULT_TIMEPICKER_CLASSES: Required<TimePickerClasses> = {
  root: "",
  label: "",
  wrapper: "",
  trigger: "",
  input: "",
  endIcon: "",
  clearIcon: "",
  dropdown: "",
  optionList: "",
  option: "",
  optionSelected: "",
  optionFocused: "",
  selectedIcon: "",
  noResults: "",
  error: "",
  description: "",
  success: "",
  clockContainer: "",
  clockDisplay: "",
  clockDisplayHours: "",
  clockDisplayMinutes: "",
  clockDisplayActive: "",
  clockDisplaySeparator: "",
  clockFace: "",
  clockHand: "",
  clockHandLine: "",
  clockHandDot: "",
  clockNumber: "",
  clockNumberSelected: "",
  clockNumberInner: "",
  clockNumberDisabled: "",
  clockCenter: "",
  clockActions: "",
  clockCancelButton: "",
  clockOkButton: "",
  clockPeriodToggle: "",
  clockPeriodButton: "",
  clockPeriodActive: "",
};

export const UNSTYLED_TIMEPICKER_CLASSES: Required<TimePickerClasses> = {
  ...DEFAULT_TIMEPICKER_CLASSES,
};
