import type { TableClasses } from "./utils/types";

export {
  DEFAULT_ROW_OPTIONS,
  DEFAULT_VISIBLE_PAGE_COUNT,
} from "../Pagination";

export const DEFAULT_TABLE_CLASSES: Required<TableClasses> = {
  container: "",
  table: "",
  header: "",
  headerRow: "",
  headerCell: "",
  headerCellHover: "",
  headerCellContent: "",
  body: "",
  row: "",
  cell: "",
  selectedRow: "",
  pinnedContainer: "",
  pinnedTable: "",
  unpinnedContainer: "",
  unpinnedTable: "",
  empty: "",
  pinIcon: "",
  pinIconHover: "",
  pinnedPinIcon: "",
  pinnedPinIconHover: "",
  pinButton: "",
  pinnedPinButton: "",
  shimmer: "",
  shimmerRow: "",
  shimmerCell: "",
  shimmerBar: "",
  checkbox: "",
  checkboxCell: "",
  sortIcon: "",
  filterInput: "",
  filterIcon: "",
  filterDropdown: "",
  expandIcon: "",
  expandedRow: "",
  pinnedRightContainer: "",
  pinnedRightTable: "",
  editInput: "",
  dragHandle: "",
  footer: "",
  searchBar: "",
  mobileCard: "",
  groupHeader: "",
  resizeHandle: "",
  loadingMore: "",
  searchInput: "",
};

export const UNSTYLED_TABLE_CLASSES: Required<TableClasses> = {
  container: "",
  table: "",
  header: "",
  headerRow: "",
  headerCell: "",
  headerCellHover: "",
  headerCellContent: "",
  body: "",
  row: "",
  cell: "",
  selectedRow: "",
  pinnedContainer: "",
  pinnedTable: "",
  unpinnedContainer: "",
  unpinnedTable: "",
  empty: "",
  pinIcon: "",
  pinIconHover: "",
  pinnedPinIcon: "",
  pinnedPinIconHover: "",
  pinButton: "",
  pinnedPinButton: "",
  shimmer: "",
  shimmerRow: "",
  shimmerCell: "",
  shimmerBar: "",
  checkbox: "",
  checkboxCell: "",
  sortIcon: "",
  filterInput: "",
  filterIcon: "",
  filterDropdown: "",
  expandIcon: "",
  expandedRow: "",
  pinnedRightContainer: "",
  pinnedRightTable: "",
  editInput: "",
  dragHandle: "",
  footer: "",
  searchBar: "",
  mobileCard: "",
  groupHeader: "",
  resizeHandle: "",
  loadingMore: "",
  searchInput: "",
};
