// Client side of the preview bridge: post code/theme into the sandboxed
// iframe (public/preview.html, generated by scripts/build-preview-vendor.mjs)
// and subscribe to its ready / rendered / error messages.
import type { VerifyError } from "../../pages/playground/types";

export const PREVIEW_PATH = "/preview.html";

export type PreviewTheme = "dark" | "light";

export type PreviewInMessage =
  | { type: "render"; code: string }
  | { type: "setTheme"; theme: PreviewTheme };

export type PreviewOutMessage =
  | { type: "ready" }
  | { type: "rendered" }
  | { type: "error"; error: VerifyError };

const OUT_TYPES = new Set(["ready", "rendered", "error"]);

export function postToPreview(
  frame: HTMLIFrameElement,
  message: PreviewInMessage
) {
  frame.contentWindow?.postMessage(message, window.location.origin);
}

export function subscribeToPreview(
  frame: HTMLIFrameElement,
  onMessage: (message: PreviewOutMessage) => void
): () => void {
  const handler = (event: MessageEvent) => {
    if (event.origin !== window.location.origin) return;
    if (event.source !== frame.contentWindow) return;
    const data = event.data as PreviewOutMessage | undefined;
    if (data && OUT_TYPES.has(data.type)) onMessage(data);
  };
  window.addEventListener("message", handler);
  return () => window.removeEventListener("message", handler);
}
