import type { StepperClasses } from "./types";

export const DEFAULT_STEPPER_CLASSES: Required<StepperClasses> = {
  root: "",
  list: "list-none m-0 p-0",
  stepContainer: "",
  step: "flex items-center gap-1.5 sm:gap-2 transition-colors motion-reduce:transition-none",
  stepInteractive:
    "cursor-pointer rounded-lg px-1.5 py-1 sm:px-2 sm:py-1.5 hover:bg-gray-50 focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-blue-500 focus-visible:ring-offset-2",
  stepDisabled: "opacity-50 cursor-not-allowed",
  indicator:
    "shrink-0 rounded-full flex items-center justify-center transition-colors motion-reduce:transition-none",
  indicatorButton:
    "cursor-pointer rounded-full focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-blue-500 focus-visible:ring-offset-2",
  indicatorIcon: "",
  indicatorActive: "bg-blue-600 text-white",
  indicatorCompleted: "bg-green-500 text-white",
  indicatorPending: "bg-gray-200 text-gray-600",
  indicatorError: "bg-red-500 text-white",
  labelWrapper: "flex flex-col",
  labelWrapperBottom: "items-center",
  label: "text-xs sm:text-sm font-medium leading-tight transition-colors motion-reduce:transition-none",
  labelActive: "text-blue-600 dark:text-blue-400",
  labelCompleted: "text-green-600 dark:text-green-400",
  labelPending: "text-gray-500",
  labelError: "text-red-500 dark:text-red-400",
  description: "text-[10px] sm:text-xs leading-tight transition-colors motion-reduce:transition-none",
  descriptionActive: "text-blue-500 dark:text-blue-400",
  descriptionCompleted: "text-green-500 dark:text-green-400",
  descriptionPending: "text-gray-400",
  descriptionError: "text-red-400 dark:text-red-300",
  connector: "transition-colors motion-reduce:transition-none",
  connectorHorizontal: "w-full h-0.5 bg-gray-200",
  connectorVertical: "w-0.5 h-6 bg-gray-200",
  connectorActive: "bg-blue-200 dark:bg-blue-800",
  connectorCompleted: "bg-green-500 dark:bg-green-600",
  connectorPending: "",
  connectorError: "",
};

export const UNSTYLED_STEPPER_CLASSES: Required<StepperClasses> = {
  root: "",
  list: "",
  stepContainer: "",
  step: "",
  stepInteractive: "",
  stepDisabled: "",
  indicator: "",
  indicatorButton: "",
  indicatorIcon: "",
  indicatorActive: "",
  indicatorCompleted: "",
  indicatorPending: "",
  indicatorError: "",
  labelWrapper: "",
  labelWrapperBottom: "",
  label: "",
  labelActive: "",
  labelCompleted: "",
  labelPending: "",
  labelError: "",
  description: "",
  descriptionActive: "",
  descriptionCompleted: "",
  descriptionPending: "",
  descriptionError: "",
  connector: "",
  connectorHorizontal: "",
  connectorVertical: "",
  connectorActive: "",
  connectorCompleted: "",
  connectorPending: "",
  connectorError: "",
};
